spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/ecomap;MODE=MYSQL
    username: sa
    password: 123
#    driver-class-name:
  jpa:
    database: h2
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: Asia/Seoul
